### ISSUE TITLE
Experimental Event `InputEvent` has readonly `data` attribute

### ISSUE THREAD

**Issue by xuorig** [madrobby/zepto#1256] opened 2017-01-19 20:17 UTC
I started getting `Uncaught TypeError: Cannot assign to read only property 'data' of object '#<InputEvent>'` with a flag on chrome.

This line being the culprit https://github.com/madrobby/zepto/blob/master/src/event.js#L68

The new `InputEvent` spec has an actual `data` attribute, clashing with Zepto's.

Seems like the real fix would be to deprecate `data` on the event and use something else, or return a custom event instead of modifying the DOM Event itself.

It will because a big problem soon when this is not experimental I believe.

cc @maximebedard @krystosterone

**Comment by madrobby** [comment] 2017-08-06 15:07
Closing this as I can't reproduce.

**Closed by madrobby** 2017-08-06 15:07 UTC
Labels: Bug, Needs tests

**Comment by leedut** [comment] 2017-08-23 02:12
Maybe you should update chrome to 60 ... I reproduced it too @madrobby

**Comment by drakmail** [comment] 2017-10-02 19:11
I'm also have same issue with jquery )

**Comment by Haroenv** [comment] 2018-02-07 12:22
This issue is happening if you add an event to the `input` event

**Comment by EmmanuelBeziat** [comment] 2018-08-23 02:03
Same issue today, with Chrome 68. Nothing in dev environment, but the error is fired on production (webpack 4).
