### ISSUE TITLE
TypeError: Attempted to assign to readonly property, in event.add method

### ISSUE THREAD

**Issue by atgwwx** [madrobby/zepto#1295] opened 2017-07-04 07:32 UTC
in iphone 10.3, when i bind `input` event , it occurs error, like below:
```
<input id="input_age">
$('#input_age').on('input',function(){
         
        });
```
![eudlh](https://user-images.githubusercontent.com/4476814/27819597-93da0e12-60cd-11e7-81ca-421eed5ec7ea.jpg)

**Comment by xuorig** [comment] 2017-07-23 18:23
Related: https://github.com/madrobby/zepto/issues/1256

Unfortunatly it seems like zepto has not been accepting Issues / PRs

**Comment by madrobby** [comment] 2017-08-06 12:39
Duplicate of #1256 1256

**Closed by madrobby** 2017-08-06 12:39 UTC
