### ISSUE TITLE
$.each leads to unexpected results 

### ISSUE THREAD

**Issue by wuzy** [madrobby/zepto#1123] opened 2015-07-11 02:10 UTC
when the $.ajax option.data has a key length, which it is value is number。for example,
```
$.ajax({
    url: 'xxx',
    data: {start: 0, length: 20}),
    xxxx
});
```
then request was: xxx?0=&1=&2=&3=&4=&5=&6=&7=&8=&9=&10=&11=&12=&13=&14=&15=&16=&17=&18=&19=

but not: xxx?length=20&start=0。

when i debug the source, i found this:
```
$.each = function(elements, callback) {
        var i, key;

        // the function likeArray get wrong result
        if (likeArray(elements)) {
            for (i = 0; i < elements.length; i++)
                if (callback.call(elements[i], i, elements[i]) === false)
                    return elements
        } else {
            for (key in elements)
                if (callback.call(elements[key], key, elements[key]) === false)
                    return elements
        }
        
        return elements
    }
    
    
    function likeArray(obj) {
        return typeof obj.length == 'number'
    }
```

**Comment by mislav** [comment] 2015-07-17 21:34
Thanks for reporting. This seems to be a duplicate of #918

**Closed by mislav** 2015-07-17 21:34 UTC
