### ISSUE TITLE
tap double trigger on chrome 55

### ISSUE THREAD

**Issue by Xaber20110202** [madrobby/zepto#1249] opened 2016-12-26 06:40 UTC
when I remove pointer event, it returns to normal

**Comment by kslimani** [comment] 2016-12-30 12:07
@Xaber20110202 what is your OS please ? do you experience this behaviour under Android only ?

**Comment by Xaber20110202** [comment] 2016-12-30 12:10
on macOS chrome 55

**Comment by Xaber20110202** [comment] 2016-12-30 12:11
thank for your reply!

**Comment by mbyor** [comment] 2016-12-31 14:24
Confirming what @Xaber20110202 reported. Since Chrome 55 for mobile is out, the tap event (coming with the touch module) is misbehaving - once it will trigger twice on single tap, other times it may not trigger at all, requiring 2nd tap for something to happen.

The reason behind this behaviour is PointerEvents added in Chrome since version 55. More info about these and why were added:

https://blog.chromium.org/2016/10/chrome-55-beta-input-handling.html
https://developers.google.com/web/updates/2016/10/pointer-events

All this means that since Chrome 55 apart from any touch event being fired (e.g. "touchstart"), Chrome will also fire the respective pointer one (e.g. "pointerdown" is fired together with "touchstart"). Zepto already has some pointer events handling added for MS Edge and IE11, which seems to be incompatible with Chrome's pointer events fired together with touch events.

To get the touch module fixed it will have to either be rewritten so to handle separately/properly pointer events fired by Chrome and MS browsers or, as a quick hack, ignore pointer events if fired and the browser is Chrome. Another solution is what @Xaber20110202 mentioned as well - to simply remove all pointer events handling from the touch module, which works very well given one doesn't have to support MS mobile browsers. This is also the quick solution I went for couple of weeks ago when stumbled upon this issue...

**Comment by MarvinXu** [comment] 2017-01-03 05:25
@mbyor cool! problem solved!

**Comment by bitfool** [comment] 2017-01-11 15:41
mbyor, MarvinXu, 
could one of you describe more clearly (code) how you code to "ignore pointer events if fired and the browser is Chrome"?  i'm not having success in my initial attempts, but it sounds like the way to go to get my old app upgraded with this more recent touch.js and back working with Chrome.

**Comment by MarvinXu** [comment] 2017-02-04 06:47
![image](https://cloud.githubusercontent.com/assets/7382357/22616435/06e83e76-eae8-11e6-8b57-4fde7db06aed.png)
@bitfool 
I simply removed all  event name containing "pointer" in the first parameter of all event binding functions...

**Comment by maobon** [comment] 2017-02-15 07:23
swipeLeft and swipeRight went wrong...

**Comment by madrobby** [comment] 2017-08-06 12:49
Duplicate of #1238

**Closed by madrobby** 2017-08-06 12:49 UTC
